# SOURCE: https://pre-commit.com/hooks.html

exclude: '^(contrib|docs/conf.py|docs/gfx)'

repos:
-   repo: local
    hooks:
    -   id: brew-style-fix
        name: brew style fix
        entry: .ci/style.sh
        language: script
        files: ^Formula/.*\.rb$
